### ISSUE TITLE
Add to the cronjob disable email alert

### ISSUE THREAD

**Issue by killmasta93** [sebastian13/zabbix-templates#1]
Hi just wanted to say thank you for the script works great, would recommend to add the

`>/dev/null 2>&1`

at the end of the cronjob

Thank you

**Comment by sebastian13** [comment]
Thanks for the hint! I guess you are talking about `speedtest/speedtest-zabbix.cron`? I will add `>/dev/null`. Receiving notifications about errors isn't that bad, right? :)
