### ISSUE TITLE
Future implementation? 

### ISSUE THREAD

**Issue by killmasta93** [sebastian13/zabbix-templates#3]
Hi,
I was wondering if its possible that i would get an alert is the rescript config is older then X days?

Thank you

**Comment by sebastian13** [comment]
Hi @killmasta93,

can you explain the reason behind this? From my understanding it's the other way round. Config files should not change on their own. Therefore you will receive a warning if the config file was changed. How does the age matter?

**Comment by killmasta93** [comment]
Thanks for the reply, so yesterday i got an email alert from rescript backup failed but on zabbix no alert i assume because in the script it runs the repo but if it finds an error it wont pass to the next line which sends to zabbix
Thank you 

```
# Enable Pipefail for exit-code logging
 set -e

# Run Backups
rescript contabilidad

#send logs to zabbix
/etc/zabbix/scripts/log-rescript.sh

#run backups
rescript usuarios
#send logs to zabbix
/etc/zabbix/scripts/log-rescript.sh

#run backups

rescript publica

#send logs to zabbix
/etc/zabbix/scripts/log-rescript.sh


#run backups

rescript sql

#send logs to zabbix
/etc/zabbix/scripts/log-rescript.sh

#unmount the share so there is not a risk of infection of input/output error change according to the mount place
umount -a -t cifs -l
exit 0

```
see picture
![Screenshot from 2020-02-14 11-58-15](https://user-images.githubusercontent.com/13953629/74551716-afca3080-4f21-11ea-9082-58a032b90408.png)


![image](https://user-images.githubusercontent.com/13953629/74552705-d1c4b280-4f23-11ea-86ce-589bedb72ed3.png)

**Comment by sebastian13** [comment]
Well, if `log-rescript.sh` isn't called, Zabbix should fire the following trigger after 2 days:

`Rescript Restic Backup on {HOST.NAME} to {#REPO} is outstanding`

This is defined in _Templates -> Template Rescript Restic Backup -> Discovery rules -> Repo Discovery -> Trigger prototypes_:

`
{Template Rescript Restic Backup:rescript.backup.snapshotid[{#REPO}].nodata(2d)}=1
`

As no data is sent to Zabbix in this case, you won't see any data in **Latest data**. The trigger however, should be fired and pop up on the **Problems** tab.

![problems-restic](https://user-images.githubusercontent.com/10852783/75353151-287aa680-58ab-11ea-8fc8-1f516afd681f.png)

**Comment by killmasta93** [comment]
Thank you so much im going to try and post back

**Comment by killmasta93** [comment]
working
